# Generated by Django 6.0.3 on 2026-06-30 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('testinnings', models.IntegerField()),
                ('runs', models.IntegerField()),
            ],
        ),
    ]
