# Generated by Django 6.0.3 on 2026-06-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField()),
                ('subject', models.CharField()),
                ('score', models.CharField()),
                ('email', models.CharField()),
            ],
        ),
    ]
