# Generated by Django 6.0.3 on 2026-07-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authname', models.CharField()),
                ('bookname', models.CharField()),
            ],
        ),
    ]
